#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct 15 16:17:49 2020

@author: nautica
"""

# diccionario vacio
midiccionario={}
midiccionario['jose']=123
midiccionario['juan']=456
print(midiccionario)
print(midiccionario['juan'])